---
- name: Ensure AWS long lived credentials are configured locally
  ansible.builtin.shell:
    cmd: |
      export AWS_DEFAULT_PROFILE=rosa_spoke
      aws configure set region ap-southeast-2 --profile rosa_spoke
      aws configure set aws_access_key_id "{{ aws_access_key_id }}" --profile rosa_spoke
      aws configure set aws_secret_access_key "{{ aws_secret_access_key }}" --profile rosa_spoke
      aws configure set profile rosa_spoke
      rosa login --token "{{ rosa_token }}"
  no_log: true
  changed_when: false

- name: Ensure AWS long lived credentials are configured on the bastion
  ansible.builtin.shell:
    cmd: |
      export AWS_DEFAULT_PROFILE=rosa_spoke
      aws configure set region ap-southeast-2 --profile rosa_spoke
      aws configure set aws_access_key_id "{{ aws_access_key_id }}" --profile rosa_spoke
      aws configure set aws_secret_access_key "{{ aws_secret_access_key }}" --profile rosa_spoke
      aws configure set profile rosa_spoke
      rosa login --token "{{ rosa_token }}"
  no_log: true
  changed_when: false
  delegate_to: bastion

- name: Get Hub cluster API URL
  ansible.builtin.shell:
    cmd: |
      export AWS_DEFAULT_PROFILE=rosa_spoke
      rosa describe cluster --cluster=hub --output=json | jq -r '.api.url'
  register: hub_api_url
  failed_when: "'Not logged in' in hub_api_url.stderr or 'Failed to find credentials' in hub_api_url.stderr"
  delegate_to: bastion

- name: Set Hub API URL
  ansible.builtin.set_fact:
    hub_api_url: "{{ hub_api_url.stdout }}"
  delegate_to: bastion

- name: Retrieve Hub authentication token
  community.okd.openshift_auth:
    username: "{{ rosa_admin_username }}"
    password: "{{ rosa_admin_password }}"
    host: "{{ hub_api_url }}"
    validate_certs: false
  register: hub_openshift_auth_results
  delegate_to: bastion

- name: "Delete {{ rosa_cluster_name }} from ACM"
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ rosa_cluster_name }}"
    state: absent
    host: "{{ hub_api_url }}"
    api_key: "{{ hub_openshift_auth_results.openshift_auth.api_key }}"
    validate_certs: false
  delegate_to: bastion

- name: "Delete {{ rosa_cluster_name }}'s PrivateLink"
  environment:
    TF_VAR_AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    TF_VAR_AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    TF_VAR_AWS_DEFAULT_REGION: "{{ rosa_region | default('ap-southeast-2') }}"
    TF_BACKEND_BUCKET: "{{ rosa_cluster_name }}-terraform"
    TF_VAR_token: "{{ rosa_token }}"
  cloud.terraform.terraform:
    project_path: "{{ work_dir }}/{{ rosa_cluster_name }}/privatelink/terraform"
    state: absent
  register: "rh.privatelink.delete"
  delegate_to: bastion

- name: "Show output"
  ansible.builtin.debug:
    msg: "{{ rh.privatelink.delete.outputs }}"
  delegate_to: bastion

- name: "Delete ROSA cluster {{ rosa_cluster_name }}"
  environment:
    TF_VAR_AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    TF_VAR_AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    TF_VAR_AWS_DEFAULT_REGION: "{{ rosa_region | default('ap-southeast-2') }}"
    TF_BACKEND_BUCKET: "{{ rosa_cluster_name }}-terraform"
    TF_VAR_token: "{{ rosa_token }}"
  cloud.terraform.terraform:
    project_path: "{{ work_dir }}/{{ rosa_cluster_name }}/terraform"
    state: absent
  register: "rh.rosa.delete"

- name: "Show output"
  ansible.builtin.debug:
    msg: "{{ rh.rosa.delete.outputs }}"