---
region: "ap-southeast-2"
aws_access_key_id: "{{ aws_access_key_id }}"
aws_secret_access_key: "{{ aws_secret_access_key }}"
rosa_version: "4.13.10"
rosa_vpc_cidr: 10.1.0.0/16
rosa_token: "{{ rosa_token }}"
work_dir: /var/tmp