# This playbook will be used by Ansible Automation Platform to deploy a `spoke` ROSA instance
- name: Run preflight checks
  vars:
    rosa_cluster_name: "{{ rosa_hub_cluster_name }}"
    rosa_subnets: "{{ rosa_hub_subnets }}"
  ansible.builtin.import_playbook: rh.rosa.preflight_hub

- name: Deploy a hub ROSA instance
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    rosa_aws_account_id: "{{ rosa_hub_aws_account_id }}"
    rosa_aws_secret_access_key: "{{ rosa_hub_aws_secret_access_key }}"
    rosa_vpc_name: "{{ rosa_hub_vpc_name }}"
    rosa_vpc_id: "{{ rosa_hub_vpc_id }}"
    rosa_cluster_name: "{{ rosa_hub_cluster_name }}"
    rosa_vpc_cidr: "{{ rosa_hub_vpc_cidr }}"
    rosa_worker_nodes: "{{ rosa_hub_worker_nodes }}"
    rosa_worker_instance_type: "{{ rosa_hub_worker_instance_type }}"
    rosa_subnets: "{{ rosa_hub_subnets }}"
  tasks:
    - name: Deploy ROSA
      ansible.builtin.import_role:
        name: rh.rosa.create
    - name: Waiting for OAuth to come up
      ansible.builtin.pause:
        echo: no
        prompt: "Waiting for OAuth to come up"
        seconds: 90
    - name: Bootstrap hub
      ansible.builtin.import_role:
        name: rh.rosa.bootstrap_hub
      delegate_to: bastion
