---
- name: Destroy a spoke ROSA instance
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    aws_account_id: "{{ aws_spoke_account_id }}"
    aws_access_key_id: "{{ aws_spoke_access_key_id }}"
    aws_secret_access_key: "{{ aws_spoke_secret_access_key }}"
    rosa_cluster_name: "{{ rosa_spoke_cluster_name }}"
  tasks:
    - name: Deploy ROSA
      ansible.builtin.import_role:
        name: rh.rosa.delete_spoke_with_bastion